%% @private
%% @doc Schema module code generation for flatbuferl.
%%
%% Generates .erl files with inlined parsed schemas, envelope encode/decode,
%% and per-message-type typed encode/decode functions.
-module(flatbuferl_codegen).

-include("flatbuferl_records.hrl").

-export([schema_to_module/3]).

%% =============================================================================
%% Public API
%% =============================================================================

%% @doc Generate an Erlang module with the parsed schema inlined as a
%% compiled term. The generated module requires no runtime schema parsing,
%% no persistent_term, and no file I/O — the schema IS the module.
%%
%% The generated module exports:
%%   - schema/0 → {Defs, Opts} (the pre-parsed schema term)
%%   - encode_envelope/2 → {ok, binary()} | {error, term()}
%%   - decode_envelope/1 → {ok, map()} | {error, term()}
%%   - encode_<type>/N, decode_<type>/1 for each Message union member
%%
%% Example:
%%   {ok, Schema} = flatbuferl:parse_schema_file("schema/my_protocol.fbs"),
%%   ok = flatbuferl_codegen:schema_to_module(Schema, my_protocol, ".").
%%
%% Writes `my_protocol.erl` to the current directory.
-spec schema_to_module(flatbuferl:schema(), module(), file:filename()) -> ok | {error, term()}.
schema_to_module({_Defs, _Opts} = Schema, ModuleName, OutDir) ->
    ModuleStr = atom_to_list(ModuleName),
    FileName = filename:join(OutDir, ModuleStr ++ ".erl"),
    Content = schema_module_content(ModuleName, Schema),
    case file:write_file(FileName, unicode:characters_to_binary(Content)) of
        ok -> ok;
        {error, _} = Err -> Err
    end.

%% =============================================================================
%% Module Content Generation
%% =============================================================================

%% @private Generate the .erl file content for a schema module.
-spec schema_module_content(module(), flatbuferl:schema()) -> iolist().
schema_module_content(ModuleName, {Defs, Opts}) ->
    ModuleStr = atom_to_list(ModuleName),
    Exports = generate_exports(Defs),
    [
        "%% @generated by flatbuferl:schema_to_module/3\n",
        "%% DO NOT EDIT — regenerate from the canonical .fbs schema.\n",
        "-module(", ModuleStr, ").\n\n",
        Exports,
        "\n",
        "%% =============================================================================\n",
        "%% Schema (pre-parsed, compiled into the beam)\n",
        "%% =============================================================================\n\n",
        "-define(SCHEMA, ",
        lists:flatten(io_lib:format("~p", [{Defs, Opts}])),
        ").\n\n",
        "-spec schema() -> flatbuferl:schema().\n",
        "schema() -> ?SCHEMA.\n\n",
        "%% =============================================================================\n",
        "%% Envelope Encoding / Decoding\n",
        "%% =============================================================================\n\n",
        generate_envelope_code(Defs),
        "\n",
        "%% =============================================================================\n",
        "%% Per-Message-Type Encoding / Decoding\n",
        "%% =============================================================================\n\n",
        generate_message_code(Defs),
        "\n"
    ].

%% =============================================================================
%% Export Generation
%% =============================================================================

%% @private Generate the -export list including per-message-type functions.
generate_exports(Defs) ->
    BaseExports = "schema/0, encode_envelope/2, decode_envelope/1",
    case maps:get('Message', Defs, undefined) of
        #union_def{members = Members} ->
            TypeExports = lists:flatmap(
                fun(Member) ->
                    Suffix = camel_to_snake(atom_to_list(Member)),
                    case maps:get(Member, Defs, undefined) of
                        #table_def{all_fields = Fields} ->
                            ReqCount = length([F || F <- Fields, F#field_def.required =:= true]),
                            Enc1 = [",\n         encode_", Suffix, "/", integer_to_list(ReqCount)],
                            Enc2 = [",\n         encode_", Suffix, "/", integer_to_list(ReqCount + 1)],
                            Dec = [",\n         decode_", Suffix, "/1"],
                            Enc1 ++ Enc2 ++ Dec;
                        _ ->
                            []
                    end
                end,
                Members
            ),
            ["-export([", BaseExports, TypeExports, "])."];
        undefined ->
            ["-export([", BaseExports, "])."]
    end.

%% =============================================================================
%% Envelope Code Generation
%% =============================================================================

%% @private Generate encode/decode functions from the Envelope table definition.
generate_envelope_code(Defs) ->
    case maps:get('Envelope', Defs, undefined) of
        #table_def{all_fields = Fields} ->
            generate_envelope_from_fields(Fields);
        undefined ->
            [
                "-spec encode_envelope(non_neg_integer(), {atom(), map()}) ->\n",
                "    {ok, binary()} | {error, term()}.\n",
                "encode_envelope(_RequestId, {MessageType, Fields}) ->\n",
                "    try\n",
                "        IOData = flatbuferl:from_map(#{message_type => MessageType, message => Fields}, schema()),\n",
                "        {ok, iolist_to_binary(IOData)}\n",
                "    catch\n",
                "        error:Reason -> {error, {encode_failed, Reason}}\n",
                "    end.\n\n",
                "-spec decode_envelope(binary()) -> {ok, map()} | {error, term()}.\n",
                "decode_envelope(Binary) ->\n",
                "    try\n",
                "        Ctx = flatbuferl:new(Binary, schema()),\n",
                "        case flatbuferl:to_map(Ctx) of\n",
                "            Envelope when is_map(Envelope) -> {ok, Envelope};\n",
                "            _ -> {error, invalid_envelope}\n",
                "        end\n",
                "    catch\n",
                "        error:Reason -> {error, {decode_failed, Reason}}\n",
                "    end.\n"
            ]
    end.

%% @private Generate envelope code from actual field definitions.
generate_envelope_from_fields(Fields) ->
    {_MsgField, EnvFields} = lists:partition(
        fun(#field_def{name = N}) -> N =:= message end,
        Fields
    ),
    VersionDefault = case lists:keyfind(version, #field_def.name, Fields) of
        #field_def{default = V} when V /= undefined -> V;
        _ -> 1
    end,
    EncodeHead = [
        "-spec encode_envelope(non_neg_integer(), {atom(), map()}) ->\n",
        "    {ok, binary()} | {error, term()}.\n",
        "encode_envelope(RequestId, {MessageType, Fields}) ->\n",
        "    Envelope = #{\n"
    ],
    FieldLines = lists:map(
        fun(#field_def{name = version}) ->
            "        version => " ++ integer_to_list(VersionDefault);
           (#field_def{name = request_id}) ->
            "        request_id => RequestId";
           (#field_def{name = timestamp_ms}) ->
            "        timestamp_ms => erlang:system_time(millisecond)";
           (#field_def{name = message_type}) ->
            "        message_type => MessageType";
           (#field_def{name = Name}) ->
            "        " ++ atom_to_list(Name) ++ " => undefined"
        end,
        EnvFields
    ),
    AllFieldLines = FieldLines ++ ["        message => Fields"],
    EncodeBody = lists:join(",\n", AllFieldLines),
    EncodeTail = [
        EncodeBody,
        "\n",
        "    },\n",
        "    try\n",
        "        IOData = flatbuferl:from_map(Envelope, schema()),\n",
        "        {ok, iolist_to_binary(IOData)}\n",
        "    catch\n",
        "        error:Reason -> {error, {encode_failed, Reason}}\n",
        "    end.\n\n"
    ],
    DecodeHead = [
        "-spec decode_envelope(binary()) -> {ok, map()} | {error, term()}.\n",
        "decode_envelope(Binary) ->\n",
        "    try\n",
        "        Ctx = flatbuferl:new(Binary, schema()),\n",
        "        case flatbuferl:to_map(Ctx) of\n",
        "            #{version := ", integer_to_list(VersionDefault),
        "} = Envelope ->\n",
        "                {ok, Envelope};\n",
        "            #{version := V} ->\n",
        "                {error, {version_mismatch, V, ",
        integer_to_list(VersionDefault), "}};\n",
        "            _ ->\n",
        "                {error, invalid_envelope}\n",
        "        end\n",
        "    catch\n",
        "        error:Reason -> {error, {decode_failed, Reason}}\n",
        "    end.\n"
    ],
    EncodeHead ++ EncodeTail ++ DecodeHead.

%% =============================================================================
%% Per-Message-Type Code Generation
%% =============================================================================

%% @private Generate per-message-type encode/decode functions from the Message union.
generate_message_code(Defs) ->
    case maps:get('Message', Defs, undefined) of
        #union_def{members = Members} ->
            lists:flatmap(
                fun(Member) ->
                    case maps:get(Member, Defs, undefined) of
                        #table_def{all_fields = Fields} ->
                            generate_message_functions(Member, Fields);
                        _ ->
                            []
                    end
                end,
                Members
            );
        undefined ->
            []
    end.

%% @private Generate encode/decode functions for a single message type.
generate_message_functions(TypeName, Fields) ->
    TypeStr = atom_to_list(TypeName),
    FunSuffix = camel_to_snake(TypeStr),
    {Required, Optional} = lists:partition(
        fun(#field_def{required = R}) -> R =:= true end,
        Fields
    ),
    EncodeFun = generate_message_encode(FunSuffix, TypeStr, Required, Optional),
    DecodeFun = generate_message_decode(FunSuffix, TypeStr),
    EncodeFun ++ DecodeFun.

%% @private Generate encode function for a message type.
generate_message_encode(FunSuffix, TypeStr, Required, Optional) ->
    ReqArgs = [snake_to_camel_var(F#field_def.name) || F <- Required],
    ReqArgStr = lists:join(", ", ReqArgs),
    ReqFieldLines = [
        "        " ++ atom_to_list(F#field_def.name) ++ " => " ++ snake_to_camel_var(F#field_def.name)
        || F <- Required
    ],
    ReqFieldsBlock = lists:join(",\n", ReqFieldLines),
    HasReq = Required /= [],
    HasOpt = Optional /= [],
    FieldsMap =
        case {HasReq, HasOpt} of
            {true, true} ->
                OptKeys = [atom_to_list(F#field_def.name) || F <- Optional],
                OptKeysStr = lists:join(", ", OptKeys),
                [
                    "    Fields0 = #{\n",
                    ReqFieldsBlock,
                    "\n",
                    "    },\n",
                    "    Fields1 = maps:merge(\n",
                    "        maps:with([", OptKeysStr, "], Opts),\n",
                    "        Fields0),\n"
                ];
            {true, false} ->
                [
                    "    Fields = #{\n",
                    ReqFieldsBlock,
                    "\n",
                    "    },\n"
                ];
            {false, true} ->
                OptKeys = [atom_to_list(F#field_def.name) || F <- Optional],
                OptKeysStr = lists:join(", ", OptKeys),
                [
                    "    Fields = maps:with([", OptKeysStr, "], Opts),\n"
                ];
            {false, false} ->
                ["    Fields = #{},\n"]
        end,
    Spec1 =
        case HasReq of
            true ->
                SpecArgs = lists:join(", ", ["term()" || _ <- Required]),
                ["-spec encode_", FunSuffix, "(", SpecArgs, ") ->\n",
                 "    {ok, binary()} | {error, term()}.\n",
                 "encode_", FunSuffix, "(", ReqArgStr, ") ->\n",
                 "    encode_", FunSuffix, "(", ReqArgStr, ", #{}).\n\n"];
            false ->
                ["-spec encode_", FunSuffix, "() ->\n",
                 "    {ok, binary()} | {error, term()}.\n",
                 "encode_", FunSuffix, "() ->\n",
                 "    encode_", FunSuffix, "(#{}).\n\n"]
        end,
    Spec2 = [
        "-spec encode_", FunSuffix, "(",
        case HasReq of true -> [lists:join(", ", ["term()" || _ <- Required]), ", "]; false -> [] end,
        "Opts :: map()) ->\n",
        "    {ok, binary()} | {error, term()}.\n",
        "encode_", FunSuffix, "(",
        case HasReq of true -> [ReqArgStr, ", "]; false -> [] end,
        "Opts) ->\n"
    ],
    FieldVar = case {HasReq, HasOpt} of
        {true, true} -> "Fields1";
        _ -> "Fields"
    end,
    Body = [
        FieldsMap,
        "    encode_envelope(0, {'", TypeStr, "', ", FieldVar, "}).\n\n"
    ],
    Spec1 ++ Spec2 ++ Body.

%% @private Generate decode function for a message type.
generate_message_decode(FunSuffix, TypeStr) ->
    [
        "%% @doc Decode a ", TypeStr, " message.\n",
        "-spec decode_", FunSuffix, "(binary()) ->\n",
        "    {ok, map()} | {error, term()}.\n",
        "decode_", FunSuffix, "(Binary) ->\n",
        "    case decode_envelope(Binary) of\n",
        "        {ok, #{message_type := '", TypeStr, "', message := Msg}} ->\n",
        "            {ok, Msg};\n",
        "        {ok, #{message_type := Other}} ->\n",
        "            {error, {unexpected_message_type, Other, '", TypeStr, "'}};\n",
        "        {error, _} = Err ->\n",
        "            Err\n",
        "    end.\n\n"
    ].

%% =============================================================================
%% String Helpers
%% =============================================================================

%% @private Convert CamelCase to snake_case for function names.
camel_to_snake(Str) ->
    camel_to_snake(Str, []).

camel_to_snake([], Acc) ->
    lists:reverse(Acc);
camel_to_snake([C | Rest], Acc) when C >= $A, C =< $Z ->
    Lower = C + ($a - $A),
    case Acc of
        [] ->
            camel_to_snake(Rest, [Lower | Acc]);
        _ ->
            camel_to_snake(Rest, [Lower, $_ | Acc])
    end;
camel_to_snake([C | Rest], Acc) ->
    camel_to_snake(Rest, [C | Acc]).

%% @private Convert snake_case atom to CamelCase variable name.
snake_to_camel_var(Name) when is_atom(Name) ->
    snake_to_camel_var(atom_to_list(Name));
snake_to_camel_var(Str) ->
    camelize(Str, true).

camelize([], _Upper) -> [];
camelize([$_ | Rest], _Upper) -> camelize(Rest, true);
camelize([C | Rest], true) when C >= $a, C =< $z ->
    [C - ($a - $A) | camelize(Rest, false)];
camelize([C | Rest], _Upper) ->
    [C | camelize(Rest, false)].